-- MySQL Script generated by MySQL Workbench
-- Tue Mar  7 16:44:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Enfermedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Enfermedad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Enfermedad` (
  `idEnfermedad` INT NOT NULL,
  `Sintomas` VARCHAR(45) NULL DEFAULT NULL,
  `FechaInclusion` DATE NULL DEFAULT NULL,
  `Prevalencia` VARCHAR(45) NULL DEFAULT NULL,
  `Genes` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEnfermedad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Articulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Articulo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Articulo` (
  `idArticulo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Articulocol` VARCHAR(45) NULL DEFAULT NULL,
  `Enfermedad_idEnfermedad` INT NOT NULL,
  PRIMARY KEY (`idArticulo`),
  INDEX `fk_Articulo_Enfermedad1_idx` (`Enfermedad_idEnfermedad` ASC) VISIBLE,
  CONSTRAINT `fk_Articulo_Enfermedad1`
    FOREIGN KEY (`Enfermedad_idEnfermedad`)
    REFERENCES `mydb`.`Enfermedad` (`idEnfermedad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Autor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Enfermedad_has_Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Enfermedad_has_Autor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Enfermedad_has_Autor` (
  `Enfermedad_idEnfermedad` INT NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`Enfermedad_idEnfermedad`, `Autor_idAutor`),
  INDEX `fk_Enfermedad_has_Autor_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  INDEX `fk_Enfermedad_has_Autor_Enfermedad1_idx` (`Enfermedad_idEnfermedad` ASC) VISIBLE,
  CONSTRAINT `fk_Enfermedad_has_Autor_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`),
  CONSTRAINT `fk_Enfermedad_has_Autor_Enfermedad1`
    FOREIGN KEY (`Enfermedad_idEnfermedad`)
    REFERENCES `mydb`.`Enfermedad` (`idEnfermedad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Proteina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proteina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proteina` (
  `idProteina` INT NOT NULL,
  `Secuencia` VARCHAR(45) NULL DEFAULT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idProteina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Enfermedad_has_Proteina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Enfermedad_has_Proteina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Enfermedad_has_Proteina` (
  `Enfermedad_idEnfermedad` INT NOT NULL,
  `Proteina_idProteina` INT NOT NULL,
  PRIMARY KEY (`Enfermedad_idEnfermedad`, `Proteina_idProteina`),
  INDEX `fk_Enfermedad_has_Proteina_Proteina1_idx` (`Proteina_idProteina` ASC) VISIBLE,
  INDEX `fk_Enfermedad_has_Proteina_Enfermedad_idx` (`Enfermedad_idEnfermedad` ASC) VISIBLE,
  CONSTRAINT `fk_Enfermedad_has_Proteina_Enfermedad`
    FOREIGN KEY (`Enfermedad_idEnfermedad`)
    REFERENCES `mydb`.`Enfermedad` (`idEnfermedad`),
  CONSTRAINT `fk_Enfermedad_has_Proteina_Proteina1`
    FOREIGN KEY (`Proteina_idProteina`)
    REFERENCES `mydb`.`Proteina` (`idProteina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
